// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zpUHCKprTYWL7eYznRFJnzzKHtNscyU',
    appId: '1:973804445867:web:f5976ab7e8249bb723d7ee',
    messagingSenderId: '973804445867',
    projectId: 'places-52b67',
    authDomain: 'places-52b67.firebaseapp.com',
    storageBucket: 'places-52b67.firebasestorage.app',
    measurementId: 'G-CL8M10HTLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTsOREfusExzvKsv6XD-8fzV4o0ChXnA',
    appId: '1:973804445867:android:186e74795039dba023d7ee',
    messagingSenderId: '973804445867',
    projectId: 'places-52b67',
    storageBucket: 'places-52b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTChJfAbR73EhfFZgVtUR_AJkF7WwgUF8',
    appId: '1:973804445867:ios:ba278e49b52cbb9223d7ee',
    messagingSenderId: '973804445867',
    projectId: 'places-52b67',
    storageBucket: 'places-52b67.firebasestorage.app',
    androidClientId: '973804445867-brlk58t493f0clrnq2g1b4tr44dvf30u.apps.googleusercontent.com',
    iosClientId: '973804445867-h6t8r68o9ibodukvlc55lp2a3g77fel6.apps.googleusercontent.com',
    iosBundleId: 'oroz.digital.gastrorate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTChJfAbR73EhfFZgVtUR_AJkF7WwgUF8',
    appId: '1:973804445867:ios:ba278e49b52cbb9223d7ee',
    messagingSenderId: '973804445867',
    projectId: 'places-52b67',
    storageBucket: 'places-52b67.firebasestorage.app',
    iosBundleId: 'oroz.digital.gastrorate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1zpUHCKprTYWL7eYznRFJnzzKHtNscyU',
    appId: '1:973804445867:web:50e96285e77867a423d7ee',
    messagingSenderId: '973804445867',
    projectId: 'places-52b67',
    authDomain: 'places-52b67.firebaseapp.com',
    storageBucket: 'places-52b67.firebasestorage.app',
    measurementId: 'G-9ZYKZ8QPJ2',
  );
}